services:
  db:
    image: postgres:14-alpine
    container_name: esoft_game_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-admin}
      POSTGRES_DB: ${POSTGRES_DB:-esoft_game_dev}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    container_name: esoft_game_backend
    restart: always
    depends_on:
      - db
    environment:
      - DATABASE_URL_DEV=postgres://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-admin}@db:5432/${POSTGRES_DB:-esoft_game_dev}
      - PORT=5000
      - JWT_SECRET=${JWT_SECRET}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules

  frontend:
    build:
      context: ./frontend
    container_name: esoft_game_frontend
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  postgres_data: 